Large update to AppCafe UI
* Reorganize the Top Level menu items, now we have the following:

System Packages | App Containers | Jails | Logout | Status

Started adding basic "Jails" functionality, can now create / destroy
jails on the fly, still working on details / info pages and
config UI.

diff --git a/src-webui/appweb/dispatcher b/src-webui/appweb/dispatcher
--- a/src-webui/appweb/dispatcher
+++ b/src-webui/appweb/dispatcher
@@ -91,7 +91,7 @@ run_queue_cmd()
             ;;
  pkgupdate) target="$origin" ;;
     iocage) case $origin in
-	       destroy|pull) ;;
+	       destroy|pull|create) ;;
 		   *) echo "Unauthorized iocage command specified: $1" >> ${QLOGFILE}
                       echo "FAILED $ident $@" >> $QRESULTS
                       return 1 ;;
@@ -125,6 +125,7 @@ run_queue_cmd()
        cmd="iocage pkgupdate $target"
      fi
   elif [ "$app" == "iocage" ];then
+     # App Container / gitjail
      if [ "$origin" = "pull" ] ; then
         neworigin="`echo $flag | sed 's|/|-|g'`"
 
@@ -133,7 +134,7 @@ run_queue_cmd()
         if [ $? -eq 0 ] ; then
 	  echo "ERROR: The plugin jail pbicage-$neworigin is already installed!" >> ${QLOGFILE}
           echo "FAILED $ident $@" >> $QRESULTS
-        fi	
+        fi
 
 	if [ -n "$(sysctl -qn kern.features.vimage)" ] ; then
           # System has VIMAGE enabled
@@ -143,6 +144,25 @@ run_queue_cmd()
 	  cmd="iocage pull $target tag=pbicage-$neworigin boot=on ip4_addr=DEFAULT|AUTOIP4"
 	fi
      fi 
+     # Regular jail creation
+     if [ "$origin" = "create" ] ; then
+        newtag="$flag"
+
+	# First make sure this jail doesn't exist
+	iocage get ip4_addr pbijail-$newtag 2>/dev/null >/dev/null
+        if [ $? -eq 0 ] ; then
+	  echo "ERROR: The plugin jail pbijail-$newtag is already installed!" >> ${QLOGFILE}
+          echo "FAILED $ident $@" >> $QRESULTS
+        fi
+
+	if [ -n "$(sysctl -qn kern.features.vimage)" ] ; then
+          # System has VIMAGE enabled
+          cmd="iocage create tag=pbijail-$newtag devfs_ruleset=5 boot=on vnet=on dhcp=on bpf=on"
+	else
+	  # No VIMAGE, use fallback method
+	  cmd="iocage create tag=pbijail-$newtag boot=on ip4_addr=DEFAULT|AUTOIP4"
+	fi
+     fi
      if [ "$origin" = "destroy" ] ; then
         # Stop the jail first
         iocage stop $target >>${QLOGFILE} 2>>${QLOGFILE}
@@ -170,7 +190,10 @@ run_queue_cmd()
 
   # If we created a new jail, lets bootstrap iocage with pkgng
   if [ "$app" = "iocage" -a "$origin" = "create" -a $err -eq 0 ] ; then
-     local jdir="/`cat ${QLOGFILE} | grep 'jail_zfs_dataset=' |cut -d '=' -f 2 | sed 's|/data$||g'`"
+     # Start the jail
+     echo "#Starting the jail..." >>${QLOGFILE}
+     iocage start pbijail-$newtag >>${QLOGFILE} 2>>${QLOGFILE}
+     local jdir="/`iocage get jail_zfs_dataset pbijail-$newtag | sed 's|/data$|/root|g'`"
      bootstrap_pkgng_iocage "$jdir" >>${QLOGFILE} 2>>${QLOGFILE}
   fi
 
@@ -224,7 +247,7 @@ unblock_jail_ip4()
 bootstrap_pkgng_iocage()
 {
   local jaildir="${1}"
-  local outfile="${1}/.pkgBS.sh"
+  local outfile="${1}/tmp/.pkgBS.sh"
   echo "Bootstrapping pkgng for jail ${jaildir}"
 
   if [ ! -e "${jaildir}/bin/freebsd-version" ] ; then
@@ -285,7 +308,7 @@ exit 0
 __EOF__
 
   # Run the file to bootstrap pkg
-  chroot $jaildir sh /.pkgBS.sh
+  chroot $jaildir sh /tmp/.pkgBS.sh
   rm ${outfile}
 
   # Now boot-strap the real pkgng pkg
@@ -637,7 +660,7 @@ case $1 in
     iocage) verify_disid
 	    case $2 in
               # These commands will be queued
-              destroy|pull) echo "$@" >>${QLIST} ;;
+              create|destroy|pull) echo "$@" >>${QLIST} ;;
 	      getip4) get_iocage_ip4 "$@" ;;
 	      addfstab) run_iocage_addfstab "$@" ;;
 	      delfstab) run_iocage_delfstab "$@" ;;
