Update AppCafe / dispatcher / bitlbee config file
* This changes how config files are created / shown on the appcafe
* Now instead of trying to make AppCafe support every variety of
  config file under the sun, module creators can provide their own
  scripts to get / set configuration data.
* This means we can work with just about any config format, including
  databases and others.

diff --git a/src-webui/appweb/dispatcher b/src-webui/appweb/dispatcher
--- a/src-webui/appweb/dispatcher
+++ b/src-webui/appweb/dispatcher
@@ -266,53 +266,76 @@ run_service_cmd()
 # Get value from config file
 getcfg()
 {
-   if [ ! -e "$cfile" ] ; then exit 0; fi
+ cscript="$pbicdir/scripts/getconfig.sh"
+ if [ ! -e "$cscript" ] ; then exit 1; fi
 
-   value=`grep "^${key}${delim}" $cfile 2>/dev/null | head -n 1 | sed "s|${key}${delim}||g"`
+ if [ "$jail" != "__system__" ] ; then
+    jid="$jail"
+    jdir=`jls | grep " ${jid} " | awk '{print $4}'`
+    rm ${jdir}/tmp/.appcafe-getcfg.sh.$$ >/dev/null 2>/dev/null
+    cp $cscript ${jdir}/tmp/.appcafe-getcfg.sh.$$
+    jexec $jid sh /tmp/.appcafe-getcfg.sh.$$ "$key"
+    err=$?
+    rm ${jdir}/tmp/.appcafe-getcfg.sh.$$
+ else
+   $cscript "$key"
+   err=$?
+ fi
 
-   # See if we have quotes to remove
-   if [ "$quotes" = "double" ] ; then value="$(echo $value | cut -d '"' -f 2)"; fi
-   if [ "$quotes" = "single" ] ; then value="$(echo $value | cut -d "'" -f 2)"; fi
-   if [ -z "$quotes" ] ; then value="$(echo $value | cut -d ' ' -f 1)"; fi
-
-   # Is there a suffix to remove?
-   if [ -n "$suffix" ] ; then value="$(echo $value | sed "s|$suffix\$||g")"; fi
-
-   echo "$value"
-
-   if [ -z "$noexit" ] ; then exit 0; fi
+ if [ $err -ne 0 ] ; then
+   echo "Failed getting key: $key"
+   exit 1
+ fi
+ exit 0
 }
 
 # Set value in config file
 setcfg()
 {
-   if [ ! -e "$cfile" ] ; then exit 0; fi
+ cscript="$pbicdir/scripts/setconfig.sh"
+ if [ ! -e "$cscript" ] ; then exit 1; fi
+ if [ "$jail" != "__system__" ] ; then
+    jid="$jail"
+    jdir=`jls | grep " ${jid} " | awk '{print $4}'`
+    rm ${jdir}/tmp/.appcafe-setcfg.sh.$$ >/dev/null 2>/dev/null
+    cp $cscript ${jdir}/tmp/.appcafe-setcfg.sh.$$
+    jexec $jid sh /tmp/.appcafe-setcfg.sh.$$ "$key" "$value"
+    err=$?
+    rm ${jdir}/tmp/.appcafe-setcfg.sh.$$
+ else
+   $cscript "$key" "$value"
+   err=$?
+ fi
 
-   noexit=1
+ if [ $err -ne 0 ] ; then
+   echo "Failed getting key: $key"
+   exit 1
+ fi
+ exit 0
+}
 
-   # Get the old value / line
-   oldvalue="$(getcfg)"
+donecfg()
+{
+ cscript="$pbicdir/scripts/doneconfig.sh"
+ if [ ! -e "$cscript" ] ; then exit 1; fi
+ if [ "$jail" != "__system__" ] ; then
+    jid="$jail"
+    jdir=`jls | grep " ${jid} " | awk '{print $4}'`
+    rm ${jdir}/tmp/.appcafe-donecfg.sh.$$ >/dev/null 2>/dev/null
+    cp $cscript ${jdir}/tmp/.appcafe-donecfg.sh.$$
+    jexec $jid sh /tmp/.appcafe-donecfg.sh.$$
+    err=$?
+    rm ${jdir}/tmp/.appcafe-donecfg.sh.$$
+ else
+   $cscript
+   err=$?
+ fi
 
-   # If no old line found, lets add it
-   if [ -z "$oldvalue" ] ; then
-     if [ -z "$quotes" ] ; then newline="${key}${delim}${value}" ; fi
-     if [ "$quotes" = "double" ] ; then newline="${key}${delim}\"${value}\"" ; fi
-     if [ "$quotes" = "single" ] ; then newline="${key}${delim}\'${value}\'" ; fi
-     if [ -n "$suffix" ] ; then newline="$newline${suffix}" ; fi
-
-     # Add the line
-     echo "$newline" >> $cfile
-   fi
-
-   # Get the complete old line
-   oldline=`grep "^${key}${delim}" $cfile 2>/dev/null | head -n 1`
-
-   # Create the new line
-   newline=`echo $oldline | sed "s|$oldvalue|$value|g"`
-
-   # Let sed work its magic
-   sed -i '' "s/^${oldline}.*/${newline}/" $cfile
-
+ if [ $err -ne 0 ] ; then
+   echo "Failed getting key: $key"
+   exit 1
+ fi
+ exit 0
 }
 
 print_usage()
@@ -323,8 +346,9 @@ print_usage()
    queue {pkg|pbi} {origin} {install/delete/info} {__system__|<jailname>}
    pkgupdate {__system__|<jailname>}
    service {start|stop|restart} {servicetag} {servicerc} {__system__|<jid>}
-   getcfg {file} {key} {delim} {quotes|double/single} {suffix}
-   setcfg {file} {key} {delim} {quotes|double/single} {suffix}
+   getcfg {pbicdir} {__system__|<jid>} {key}
+   setcfg {pbicdir} {__system__|<jid>} {key} {value}
+   donecfg {pbicdir} {__system__|<jid>}
    daemon
    status
    results 
@@ -356,10 +380,12 @@ case $1 in
        log) display_log "$2" ;;
     status) list_status ;;
    results) list_results ;;
-    getcfg) cfile="$2" ; key="$3" ; delim="$4" quotes="$5" suffix="$6"
+    getcfg) pbicdir="$2" ; jail="$3" ; key="$4"
             getcfg ;;
-    setcfg) cfile="$2" ; key="$3" ; delim="$4" quotes="$5" suffix="$6" value="$7"
+    setcfg) pbicdir="$2" ; jail="$3" ; key="$4" ; value="$5"
             setcfg ;;
+   donecfg) pbicdir="$2" ; jail="$3"
+            donecfg ;;
          *) print_usage ; exit 1 ;;
 esac
 
