Now it encrypts all files properly

diff --git a/src-sh/xtrafiles/local/bin/enable_user_pefs b/src-sh/xtrafiles/local/bin/enable_user_pefs
--- a/src-sh/xtrafiles/local/bin/enable_user_pefs
+++ b/src-sh/xtrafiles/local/bin/enable_user_pefs
@@ -5,6 +5,12 @@
 
 PEFSDBDIR="/var/db/pefs"
 
+# Check if we can safely enable PEFS on this system
+if [ ! -e "/boot/kernel/pefs.ko" ] ; then
+   echo "Error: Requires PEFS in base system!"
+   exit 1
+fi
+
 USER="$1"
 USERPW="$2"
 
@@ -19,21 +25,27 @@ if [ -z "$USERHOMEDIR" -o ! -d "${USERHOMEDIR}" ] ; then
    exit 1
 fi
 
+if [ "${USERHOMEDIR}" = "/" ] ; then
+   echo "Invalid HOMEDIR = / "
+   exit 1
+fi
+
 if [ "$USERHOMEDIR" != "`realpath ${USERHOMEDIR}`" ] ; then
-  echo "Warning: PEFS will not work with sym-linked home dirs.."
+  NEWDIR=`realpath $USERHOMEDIR`
+  echo "Updating sym-linked home dir ${USERHOMEDIR} -> ${NEWDIR}"
+  OLDLINE=`cat /etc/master.passwd | grep "^${USER}:" | cut -d ':' -f 4-`
+  NEWLINE=`echo $OLDLINE | sed "s|:${USERHOMEDIR}:|:${NEWDIR}:|g"`
+  sed -i '.bak' "s|${OLDLINE}|${NEWLINE}|g" /etc/master.passwd
+  pwd_mkdb -p /etc/master.passwd
   USERHOMEDIR=`realpath $USERHOMEDIR`
 fi
 
-if [ "$USERHOMEDIR" = '/' ] ; then
-  echo "Bad USERHOMEDIR = /"
-  exit 1
-fi
-
 echo "Encrypting ${USERHOMEDIR}"
-#umount ${USERHOMEDIR} 2>/dev/null
 
-tar cvf /usr/home/.USER.$$ -C ${USERHOMEDIR} . 2>/dev/null
-rm -rf ${USERHOMEDIR}/*
+mkdir ${USERHOMEDIR}.$$
+tar cvf - -C "${USERHOMEDIR}" . 2>/dev/null | tar xvpf - -C "${USERHOMEDIR}.$$" 2>/dev/null
+rm -rf ${USERHOMEDIR}/* 2>/dev/null
+rm -rf ${USERHOMEDIR}/.* 2>/dev/null
 chown ${USER}:${USER} ${USERHOMEDIR}
 
 pefs mount ${USERHOMEDIR} ${USERHOMEDIR}
@@ -41,9 +53,7 @@ echo "${USERPW}" | pefs addkey -v -j - ${USERHOMEDIR}
 echo "${USERPW}" | pefs addchain -v -j - -Z ${USERHOMEDIR}
 
 mv ${USERHOMEDIR}/.pefs.db /tmp/.pefs.db.$$
-tar xvf /usr/home/.USER.$$ -C ${USERHOMEDIR} 2>/dev/null
-sync
-chown -R ${USER}:${USER} ${USERHOMEDIR}
+tar cvf - -C "${USERHOMEDIR}.$$" . 2>/dev/null | tar xvpf - -C "${USERHOMEDIR}" 2>/dev/null
 
 umount ${USERHOMEDIR}
 
@@ -51,7 +61,8 @@ mv /tmp/.pefs.db.$$ ${USERHOMEDIR}/.pefs.db
 chown ${USER}:${USER} ${USERHOMEDIR}/.pefs.db
 
 pefs mount ${USERHOMEDIR} ${USERHOMEDIR}
-rm /usr/home/.USER.$$ 
+rm -rf "${USERHOMEDIR}.$$"
+
 
 # Make sure the DBDIR exists
 if [ ! -d "${PEFSDBDIR}" ]; then
@@ -64,3 +75,6 @@ if [ $? -ne 0 ] ; then
   echo "${USERHOMEDIR}" >> ${PEFSDBDIR}/auto_mounts
 fi
 
+# Copy /etc/pam.d/ template files
+cp /usr/local/share/pcbsd/pefs/other /etc/pam.d/other
+cp /usr/local/share/pcbsd/pefs/system /etc/pam.d/system
