Change pc-updatemanager, don't update the pkg database at install time, unless we fail to install ports-mgmt/pkg, such as when PKG changes version and needs the update.
This fixes an issue where the update tries downloading packages
again, when we already have a "good" set on disk and database

diff --git a/src-sh/pcbsd-utils/pc-updatemanager/pc-updatemanager b/src-sh/pcbsd-utils/pc-updatemanager/pc-updatemanager
--- a/src-sh/pcbsd-utils/pc-updatemanager/pc-updatemanager
+++ b/src-sh/pcbsd-utils/pc-updatemanager/pc-updatemanager
@@ -1295,9 +1295,15 @@ tar xvpf ${REALPKGDLCACHE}/${PKGFILENAME} -C / /usr/local/sbin/pkg-static >/dev/
 PKG_CFLAG=\"-C /tmp/.pkgUpdate.conf\"
 echo \"PKG_CACHEDIR: $PKGDLCACHE\" > /tmp/.pkgUpdate.conf
 
-/usr/local/sbin/pkg-static \${PKG_CFLAG} update
 /usr/local/sbin/pkg-static \${PKG_CFLAG} ${PKG_FLAG} install -U -y -f ports-mgmt/pkg
-if [ \$? -ne 0 ] ; then exit 1; fi
+if [ \$? -ne 0 ] ; then
+  # If we fail to install pkgng, try updating first
+  /usr/local/sbin/pkg-static \${PKG_CFLAG} update
+  /usr/local/sbin/pkg-static \${PKG_CFLAG} ${PKG_FLAG} install -U -y -f ports-mgmt/pkg
+  if [ \$? -ne 0 ] ; then
+    exit 1
+  fi
+fi
 cd ${REALPKGDLCACHE}
 
 # Need to export this before installing pkgs, some scripts may try to be interactive
