Also do the same fix on master, install *-base packages last

diff --git a/src-sh/pcbsd-utils/pc-updatemanager/pc-updatemanager b/src-sh/pcbsd-utils/pc-updatemanager/pc-updatemanager
--- a/src-sh/pcbsd-utils/pc-updatemanager/pc-updatemanager
+++ b/src-sh/pcbsd-utils/pc-updatemanager/pc-updatemanager
@@ -1453,14 +1453,6 @@ mkdir -p /compat/linux/sys
 mkdir -p /compat/linux/usr
 ln -s /usr/home /compat/linux/usr/home
 
-echo \"Installing $SYSBASEORIGIN...\"
-pkg \${PKG_CFLAG} ${PKG_FLAG} install -U -y $SYSBASEORIGIN 2>&1 | tee /pkg-add.log
-if [ \$? -ne 0 ] ; then
-  cat /pkg-add.log
-  echo "FAILED INSTALLING $SYSBASEORIGIN"
-  exit 1
-fi
-
 while read pkgLine
 do
   pkgOrigin=\"\`echo \$pkgLine | cut -d ' ' -f 1\`\"
@@ -1481,6 +1473,14 @@ do
   fi
 done < /install-pkg-list
 rm /pkg-add.log
+
+echo \"Installing $SYSBASEORIGIN...\"
+pkg \${PKG_CFLAG} ${PKG_FLAG} install -U -y $SYSBASEORIGIN 2>&1 | tee /pkg-add.log
+if [ \$? -ne 0 ] ; then
+  cat /pkg-add.log
+  echo "FAILED INSTALLING $SYSBASEORIGIN"
+  exit 1
+fi
 
 echo \"Extracting ports overlay...\"
 /usr/local/bin/pc-extractoverlay ports
