Major update to the pc-updatemanager utility.
Change how we perform updates to new "major" releases of Free/PC-BSD

Now, instead of relying on the always failing pkgng upgrade system, use
the pc-updatemanager to build lists of the old system pbis/pkgs/metapkgs
, install the new world / kernel and then re-install the PBIs / metapkgs.

As a bonus, we will now keep these lists, and generate a summary file which
can be used post-install to diagnose any potential problems during the upgrade.

I still need to finish some additional parsing to grab any user-installed pkgng
apps.

diff --git a/src-sh/pc-updatemanager/pc-updatemanager b/src-sh/pc-updatemanager/pc-updatemanager
--- a/src-sh/pc-updatemanager/pc-updatemanager
+++ b/src-sh/pc-updatemanager/pc-updatemanager
@@ -419,13 +419,62 @@ finish_major_fbsd_update() {
   PATH="${PATH}:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin"
   export PATH
 
+  # Set some status variables
+  PKGSTATUS=0
+  PBISTATUS=0
+  FREEBSDSTATUS=0
+  GRUBSTATUS=0
+  METASTATUS=0
+
+  # Clear any old summary files
+  rm /root/.failed-pkgs 2>/dev/null
+  rm /root/.failed-meta 2>/dev/null
+  rm /root/.failed-pbi 2>/dev/null
+  rm /root/.failed-freebsd 2>/dev/null
+  rm /root/.failed-grub 2>/dev/null
+
+  # Is this a desktop or server?
+  if [ -e "/usr/local/bin/pc-softwaremanager" ] ; then
+     SYSTYPE="desktop"
+  else
+     SYSTYPE="server"
+  fi
+
+  # Remove all PBIs
+  clear
+  echo "Removing PBIs..."
+  while read pbi
+  do
+    echo "Removing: ${pbi}"
+    pbi_delete $pbi >/dev/null 2>/dev/null
+    if [ $? -ne 0 ] ; then
+       echo "Warning: Failed to remove: $pbi"
+       sleep 5
+    fi
+  done < /root/pcbsd-pbi-before-update
+  echo "Done!"
+
+  # Start the package cleanup process
+  clear
+  echo "Removing packages...This may take a while...\c"
+  pkg delete -afy
+  if [ $? -ne 0 ] ; then
+     echo "Warning: Failed to remove all packages"
+     sleep 5
+  fi
+  echo "Done!"
+
+  # Start the freebsd-update process
+  clear
   echo "Installing FreeBSD updates... Please wait..."
-  freebsd-update --non-interactive install
+  freebsd-update --non-interactive install | tee /root/.failed-freebsd
   if [ $? -ne 0 ] ; then
      echo "Warning: Failed running freebsd-update install!"
      echo "Press ENTER to continue"
+     FREEBSDSTATUS=1
      read tmp
   fi
+  clear
 
   # Remove this, causes all kinds of havok during the update
   if [ -e "/etc/pkg/FreeBSD.conf" ] ; then
@@ -438,31 +487,172 @@ finish_major_fbsd_update() {
   # Enable networking
   /etc/rc.d/devfs restart
   /etc/rc.d/netif restart
+  /etc/rc.d/devd start
+  /etc/rc.d/wpa_supplicant start
+  /etc/rc.d/dhclient start
   sleep 8
   clear
 
-  # Now its time to force a pkg-update of all packages to their new FreeBSD compiled versions
-  pc-updatemanager pkgupdate -f
+  # This is super-lame, we can't just remove all packages *except* pkgng, so we have to re-bootstrap
+  # Lets extract the new pkgng we fetched earlier
+  echo "Boot-Strapping PKGNG..."
+  if [ ! -d "/usr/local/etc/pkg/fingerprints/pcbsd/revoked" ] ; then
+     mkdir "/usr/local/etc/pkg/fingerprints/pcbsd/revoked"
+  fi
+  cd /
+  tar xvpf /usr/local/tmp/pkg.txz /usr/local/sbin/pkg-static >/dev/null 2>/dev/null
+  /usr/local/sbin/pkg-static install -y ports-mgmt/pkg
   if [ $? -ne 0 ] ; then
-     echo "Warning: Failed running 'pc-updatemanager pkgupdate -f'"
+     echo "Warning: Failed to re-install PKGNG..."
      echo "Press ENTER to continue"
      read tmp
   fi
 
+  # Lets update the pkgng repo
+  pkg-static update -f
+
+  # Now lets begin re-installing packages
+  if [ "$SYSTYPE" = "desktop" ] ; then
+    echo "Installing desktop packages..."
+    pkg-static install -y pcbsd-base
+    if [ $? -ne 0 ] ; then
+       PKGSTATUS=1
+       echo "pcbsd-base" >> /root/.failed-pkgs
+       echo "Warning: Failed to install pcbsd-base!"
+       echo "You will need to manually install this package to re-enable the PC-BSD desktop"
+       echo "Press ENTER to continue"
+       read tmp
+    fi
+    pc-extractoverlay desktop
+  else
+    echo "Installing server packages..."
+    pkg-static install -y trueos-base
+    if [ $? -ne 0 ] ; then
+       PKGSTATUS=1
+       echo "trueos-base" >> /root/.failed-pkgs
+       echo "Warning: Failed to install trueos-base!"
+       echo "You will need to manually install this package for the TrueOS utils."
+       echo "Press ENTER to continue"
+       read tmp
+    fi
+    pc-extractoverlay server
+  fi
+
+  # Start pbid, so that by the time meta-packages are done, we have a full index
+  rm /var/db/pbi/index/*
+  /usr/local/etc/rc.d/pbid start >/dev/null 2>/dev/null
+
+  clear
+
+  clear
+  echo "Re-Installing meta-packages"
+  while read newmeta
+  do
+    pc-metapkgmanager add $newmeta
+    if [ $? -ne 0 ] ; then
+       METASTATUS=1
+       echo "$newmeta" >> /root/.failed-meta
+       echo "Warning: Failed to re-install meta-package: $newmeta"
+       echo "Press ENTER to continue"
+       read tmp
+    fi
+  done < /root/pcbsd-meta-before-update
+
+  clear
+  echo "Re-Installing PBIs"
+  while read newpbi
+  do
+    shortpbi="`echo $newpbi | rev | cut -d '-' -f 3- | rev`"
+    pbi_add -r $shortpbi
+    if [ $? -ne 0 ] ; then
+       PBISTATUS=1
+       echo "$shortpbi" >> /root/.failed-pbi
+       echo "Warning: Failed to re-install PBI: $shortpbi"
+       echo "Press ENTER to continue"
+       read tmp
+    fi
+  done < /root/pcbsd-pbi-before-update
+
+
   # Last but not least, lets make sure to re-stamp GRUB in case any loader.conf.pcbsd modules changed
-  grub-mkconfig -o /boot/grub/grub.cfg
+  grub-mkconfig -o /boot/grub/grub.cfg | tee /root/.failed-grub
   if [ $? -ne 0 ] ; then
+     GRUBSTATUS=1
      echo "Warning: Failed running 'grub-mkconfig -o /boot/grub/grub.cfg'"
      echo "Press ENTER to continue"
      read tmp
   fi
 
-  echo "Updating overlay files..."
-  if [ -e "/usr/local/bin/pc-softwaremanager" ] ; then
-    pc-extractoverlay desktop
+
+  # Now lets show a summary
+  clear
+
+  echo "PC-BSD `uname -r` Upgrade Summary - (`date`)" > /root/pcbsd-update-summary
+  echo "-----------------------------------------------------" >> /root/pcbsd-update-summary
+
+  if [ $FREEBSDSTATUS -eq 0 ] ; then
+    echo "FreeBSD: The base-system updated successfully!" >> /root/pcbsd-update-summary
   else
-    pc-extractoverlay server
+    echo "FreeBSD: The base-system failed to install:" >> /root/pcbsd-update-summary
+    cat /root/.failed-freebsd >> /root/pcbsd-update-summary
   fi
+
+  echo "" >> /root/pcbsd-update-summary
+
+  if [ $PKGSTATUS -eq 0 ] ; then
+    echo "PKG: All packages updated successfully!" >> /root/pcbsd-update-summary
+  else
+    echo "PKG: The following packages failed to install:" >> /root/pcbsd-update-summary
+    cat /root/.failed-pkgs >> /root/pcbsd-update-summary
+  fi
+
+  echo "" >> /root/pcbsd-update-summary
+
+  if [ $METASTATUS -eq 0 ] ; then
+    echo "META: All meta-packages updated successfully!" >> /root/pcbsd-update-summary
+  else
+    echo "META: The following meta-packages failed to install:" >> /root/pcbsd-update-summary
+    cat /root/.failed-meta >> /root/pcbsd-update-summary
+  fi
+
+  echo "" >> /root/pcbsd-update-summary
+
+  if [ $PBISTATUS -eq 0 ] ; then
+    echo "PBI: All meta-packages updated successfully!" >> /root/pcbsd-update-summary
+  else
+    echo "PBI: The following meta-packages failed to install:" >> /root/pcbsd-update-summary
+    cat /root/.failed-pbi >> /root/pcbsd-update-summary
+  fi
+
+  echo "" >> /root/pcbsd-update-summary
+
+  if [ $GRUBSTATUS -eq 0 ] ; then
+    echo "GRUB: The GRUB boot-loader menus re-built successfully!" >> /root/pcbsd-update-summary
+  else
+    echo "GRUB: The GRUB boot-loader menus failed to rebuild:" >> /root/pcbsd-update-summary
+    cat /root/.failed-grub >> /root/pcbsd-update-summary
+  fi
+
+  echo "Old system information: " >> /root/pcbsd-update-summary
+  echo "/root/pcbsd-pkg-before-update" >> /root/pcbsd-update-summary
+  echo "/root/pcbsd-pbi-before-update" >> /root/pcbsd-update-summary
+  echo "/root/pcbsd-meta-before-update" >> /root/pcbsd-update-summary
+
+  echo "" >> /root/pcbsd-update-summary
+
+  echo "This summary location: /root/pcbsd-update-summary" >> /root/pcbsd-update-summary
+
+  # Clear any old summary files
+  rm /root/.failed-pkgs 2>/dev/null
+  rm /root/.failed-meta 2>/dev/null
+  rm /root/.failed-pbi 2>/dev/null
+  rm /root/.failed-grub 2>/dev/null
+  rm /root/.failed-freebsd 2>/dev/null
+
+  more /root/pcbsd-update-summary
+
+  echo "Press ENTER to reboot"
+  read tmp
 
   exit 0
 }
@@ -496,6 +686,11 @@ start_major_fbsd_update() {
      rollback_update
      exit_err "Failed downloading pkgng update..."
   fi
+
+  # Now lets build some lists of what is present on this system now
+  pkg info > /root/pcbsd-pkg-before-update
+  pbi_info > /root/pcbsd-pbi-before-update
+  pc-metapkgmanager list-installed > /root/pcbsd-meta-before-update
 
   # Lets install pkgng update
   PKGROLLBACK="YES"
