Fix pc-updatemanager, always upgrade pkgng before checking for new updates to the rest of your packages. This helps fix some issues with the package system getting stuck in an "update loop"

diff --git a/src-sh/pc-updatemanager/pc-updatemanager b/src-sh/pc-updatemanager/pc-updatemanager
--- a/src-sh/pc-updatemanager/pc-updatemanager
+++ b/src-sh/pc-updatemanager/pc-updatemanager
@@ -1148,6 +1148,13 @@ checkup_pkgs() {
   # Update the repo DB
   rc_halt "${PKG_CMD} update"
 
+  # Make sure we always have an updated pkgng before attempting to
+  # check for updates
+  ${PKG_CMD} ${PKG_FLAG} upgrade -y pkg
+  if [ $? -ne 0 ] ; then
+     echo "Warning: Failed to upgrade pkgng.."
+  fi
+
   ${PKG_CMD} ${PKG_FLAG} upgrade -n >/tmp/.pkgData.$$
   if [ $? -ne 0 ] ; then
      echo "Error checking for package updates..."
