Fix a critical bug with boot-environments. When the 1st dataset gets deleted we need to re-run grub-install to make sure it updates which dataset to pull its configuration from.

diff --git a/src-sh/pc-extractoverlay/ports-overlay/usr/local/sbin/grub-mkconfig b/src-sh/pc-extractoverlay/ports-overlay/usr/local/sbin/grub-mkconfig
--- a/src-sh/pc-extractoverlay/ports-overlay/usr/local/sbin/grub-mkconfig
+++ b/src-sh/pc-extractoverlay/ports-overlay/usr/local/sbin/grub-mkconfig
@@ -281,22 +281,45 @@ fi
 # copied to the /default/ ZFS BE
 check_grub_zfs_be()
 {
+
+  ROOTFS=`mount | awk '/ \/ / {print $1}'`
+  BEDS="$( echo ${ROOTFS} | awk -F '/' '{print $2}' )"
+  if [ "$BEDS" = "dev" ] ; then BEDS="ROOT"; fi
+
   if [ "$grub_cfg" = "/boot/grub/grub.cfg" ] ; then
-    dTank=`beadm list -a 2>/dev/null | grep '/ROOT/default' | awk '{print $1}'`
-    if ! mount | grep -q "$dTank on / ("; then
-       echo -e "Copying grub.cfg to $dTank...\c" >&2
-       fMnt="/mnt.$$"
-       mkdir $fMnt
-       if ! mount -t zfs ${dTank} $fMnt ; then
-          echo "Failed to mount ${dTank}" >&2
-          return
-       else
-         cp ${grub_cfg} ${fMnt}/boot/grub/grub.cfg
-         echo -e "done" >&2
-         umount ${fMnt} >/dev/null
-         rmdir ${fMnt} >/dev/null
-       fi
-    fi
+    for i in `beadm list -a 2>/dev/null | grep "/${BEDS}/" | awk '{print $1}'`
+    do
+      if ! mount | grep -q "$dTank on / ("; then
+         echo -e "Copying grub.cfg to $dTank...\c" >&2
+         fMnt="/mnt.$$"
+         mkdir $fMnt
+         if ! mount -t zfs ${dTank} $fMnt ; then
+            echo "Failed to mount ${dTank}" >&2
+            return
+         else
+           cp ${grub_cfg} ${fMnt}/boot/grub/grub.cfg
+           echo -e "done" >&2
+           umount ${fMnt} >/dev/null
+           rmdir ${fMnt} >/dev/null
+         fi
+      fi
+    done
+
+    # Check if we can re-stamp the boot-loader
+    TANK=`echo $ROOTFS | cut -d '/' -f 1`
+    for i in `zpool status $TANK | grep ONLINE | awk '{print $1}'`
+    do
+       if [ ! -e "/dev/${i}" ] ; then continue; fi
+       disk=`echo $i | sed 's|.eli||g'`
+
+       # Now get the root of the disk
+       disk=`echo $disk | sed 's|p[1-9]$||g' | sed "s|s[1-9][a-z]||g"`
+       if [ ! -e "/dev/${disk}" ] ; then continue; fi
+
+       # Re-install GRUB on this disk
+       echo "Installing GRUB to $disk" >&2
+       grub-install /dev/${disk}
+    done
   fi
 
 }
